export const WishList = [
  {
    id: 1,
    imgSrc: "/week1/img/dessert/eggtart.jpeg",
    title: "에그타르트",
    price: "10000",
    category: "dessert",
  },
  {
    id: 2,
    imgSrc: "/week1/img/dessert/strawberrycake.jpeg",
    title: "딸기생크림케이크",
    price: "30000",
    category: "dessert",
  },
  {
    id: 3,
    imgSrc: "/week1/img/dessert/yogurt.jpeg",
    title: "요거트 아이스크림의 정석",
    price: "10000",
    category: "dessert",
  },
  {
    id: 4,
    imgSrc: "/week1/img/dessert/shake.jpeg",
    title: "단백질 쉐이크",
    price: "5000",
    category: "dessert",
  },
  {
    id: 5,
    imgSrc: "/week1/img/dessert/salmon.jpeg",
    title: "연어초밥",
    price: "17000",
    category: "dessert",
  },
  {
    id: 6,
    imgSrc: "/week1/img/paper/baemin.png",
    title: "배민상품권 1만원",
    price: "10000",
    category: "paper",
  },
  {
    id: 7,
    imgSrc: "/week1/img/paper/oliveyoung.jpeg",
    title: "올리브영 상품권 2만원",
    price: "20000",
    category: "paper",
  },
  {
    id: 8,
    imgSrc: "/week1/img/paper/baeskin.jpeg",
    title: "배스킨라빈스 상품권 1만원",
    price: "10000",
    category: "paper",
  },
  {
    id: 9,
    imgSrc: "/week1/img/paper/starbucks.avif",
    title: "스타벅스 상품권 1만원",
    price: "10000",
    category: "paper",
  },
  {
    id: 10,
    imgSrc: "/week1/img/paper/gs25.jpeg",
    title: "GS25 편의점 1만원권",
    price: "10000",
    category: "paper",
  },
  {
    id: 11,
    imgSrc: "/week1/img/routine/necklace.jpeg",
    title: "로제 목걸이",
    price: "99000",
    category: "routine",
  },
  {
    id: 12,
    imgSrc: "/week1/img/routine/cerealbowl.jpeg",
    title: "우드 시리얼 볼",
    price: "20000",
    category: "routine",
  },
  {
    id: 13,
    imgSrc: "/week1/img/routine/handcream.jpeg",
    title: "탬버린즈 핸드크림",
    price: "18000",
    category: "routine",
  },
  {
    id: 14,
    imgSrc: "/week1/img/routine/tumbler.jpeg",
    title: "스탠리 텀블러",
    price: "30000",
    category: "routine",
  },
  {
    id: 15,
    imgSrc: "/week1/img/routine/masage.jpeg",
    title: "눈 피로회복 마사지기",
    price: "25000",
    category: "routine",
  },
];
